{% set name = "NeXpy" %}
{% set version = "0.13.1" %}
{% set sha256 = "ef8d7ae0526ab220b52d38a2ba0c375167663df6cf4660455da6fc555c60e880" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/NeXpy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - nexpy = nexpy.nexpygui:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - numpy
    - pip
    - setuptools
  run:
    - python
    - ansi2html
    - h5py
    - ipykernel >=5.2.0
    - ipython
    - lmfit
    - matplotlib
    - nexusformat >=0.5.3
    - numpy
    - pillow
    - pylatexenc
    - pyqt <=5.13
    - qtconsole
    - qtpy
    - scipy

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.functions
    - nexpy.definitions
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers
  commands:
    - nexpy --help
    - nexpy --version

about:
  home: http://nexpy.github.io/nexpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
  doc_url: https://nexpy.github.io/nexpy
  dev_url: https://github.com/nexpy/nexpy
